# Generated by Django 4.2 on 2024-12-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shot_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='movement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='scene_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
