# Generated by Django 4.2 on 2024-12-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_storyboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storyboards/'),
        ),
    ]
